export const rentPayments = [
  {
    name: "Alex Johnson",
    role: "Fletcher",
    paid: true,
    lastPaymentDate: "2025-05-06",
    totalPaid: 1950,
    monthlyRent: 650,
    paidThisMonth: 650,
  },
  {
    name: "Sarah Miller",
    role: "Fletcher",
    paid: false,
    lastPaymentDate: null,
    totalPaid: 725,
    monthlyRent: 725,
    paidThisMonth: 0,
  },
  {
    name: "Michael Chen",
    role: "Fletcher",
    paid: true,
    lastPaymentDate: "2025-05-03",
    totalPaid: 1300,
    monthlyRent: 650,
    paidThisMonth: 650,
  },
  {
    name: "Emily Davis",
    role: "Fletcher",
    paid: false,
    lastPaymentDate: null,
    totalPaid: 0,
    monthlyRent: 700,
    paidThisMonth: 0,
  },
  {
    name: "James Smith",
    role: "Fletcher",
    paid: true,
    lastPaymentDate: "2025-05-01",
    totalPaid: 2100,
    monthlyRent: 700,
    paidThisMonth: 700,
  },
  {
    name: "Olivia Brown",
    role: "Fletcher",
    paid: false,
    lastPaymentDate: null,
    totalPaid: 700,
    monthlyRent: 700,
    paidThisMonth: 0,
  },
  {
    name: "William Lee",
    role: "Fletcher",
    paid: true,
    lastPaymentDate: "2025-05-04",
    totalPaid: 1400,
    monthlyRent: 700,
    paidThisMonth: 700,
  },
  {
    name: "Sophia Wilson",
    role: "Fletcher",
    paid: false,
    lastPaymentDate: null,
    totalPaid: 0,
    monthlyRent: 650,
    paidThisMonth: 0,
  },
  {
    name: "Benjamin Clark",
    role: "Fletcher",
    paid: true,
    lastPaymentDate: "2025-05-02",
    totalPaid: 1300,
    monthlyRent: 650,
    paidThisMonth: 650,
  },
  {
    name: "Ava Martinez",
    role: "Fletcher",
    paid: false,
    lastPaymentDate: null,
    totalPaid: 650,
    monthlyRent: 650,
    paidThisMonth: 0,
  },
];

export const history = [
  {
    name: "Alex Johnson",
    department: "Fletcher",
    monthlyRent: 650,
    totalPaid: 3900,
    may: true,
    april: true,
    march: true,
    february: true,
    january: true,
    december: true,
  },
  {
    name: "Sarah Miller",
    department: "Fletcher",
    monthlyRent: 725,
    totalPaid: 725,
    may: false,
    april: true,
    march: false,
    february: false,
    january: false,
    december: false,
  },
  {
    name: "Michael Chen",
    department: "Culinary",
    monthlyRent: 550,
    totalPaid: 1350,
    additionalKitchenHours: 20,
    may: true,
    april: true,
    march: true,
    february: false,
    january: false,
    december: false,
  },
  {
    name: "Emily Parker",
    department: "Fletcher",
    monthlyRent: 675,
    totalPaid: 1350,
    may: true,
    april: false,
    march: true,
    february: false,
    january: false,
    december: false,
  },
  {
    name: "David Thompson",
    department: "Culinary",
    monthlyRent: 600,
    totalPaid: 525,
    additionalKitchenHours: 15,
    may: false,
    april: false,
    march: true,
    february: false,
    january: false,
    december: false,
  },
  {
    name: "Jessica Lee",
    department: "Culinary",
    monthlyRent: 575,
    totalPaid: 525,
    additionalKitchenHours: 10,
    may: false,
    april: true,
    march: false,
    february: false,
    january: false,
    december: false,
  },
  {
    name: "Robert Wilson",
    department: "Culinary",
    monthlyRent: 625,
    totalPaid: 1170,
    additionalKitchenHours: 8,
    may: true,
    april: true,
    march: false,
    february: false,
    january: false,
    december: false,
  },
];
